In [1]:
import numpy as np


In [2]:
arr_1 = np.array([10,12,32,34,54,66,92,100,54,23,87,69])

In [3]:
print (arr_1.reshape(4,3))

[[ 10  12  32]
 [ 34  54  66]
 [ 92 100  54]
 [ 23  87  69]]


In [4]:
arr_2 = arr_1*10
print (np.vstack((arr_1,arr_2)))

[[  10   12   32   34   54   66   92  100   54   23   87   69]
 [ 100  120  320  340  540  660  920 1000  540  230  870  690]]


In [5]:
arr_1.reshape(4,3).T

array([[ 10,  34,  92,  23],
       [ 12,  54, 100,  87],
       [ 32,  66,  54,  69]])