In [1]:
import numpy as np

In [2]:
student_data = np.random.randint(10,20,(20,5))
print (student_data)

[[15 14 13 17 10]
 [17 17 12 15 18]
 [10 15 19 11 10]
 [12 11 11 17 13]
 [16 13 12 12 16]
 [19 10 14 13 10]
 [11 17 16 12 19]
 [18 16 10 10 13]
 [14 18 15 11 11]
 [17 13 10 18 15]
 [12 19 19 19 13]
 [16 15 17 16 19]
 [13 19 16 19 15]
 [13 17 18 16 17]
 [17 10 16 14 13]
 [15 19 14 13 19]
 [16 11 16 19 14]
 [15 16 17 15 15]
 [14 11 11 18 10]
 [12 18 14 15 11]]
